config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create], path_names: {new: 'new'}

  get '/users/:id', to: 'users#show', as: 'user'

  get '/signup', to: 'users#new'

  get '/', to: 'pages#home'

  get 'pages/contact'

  get 'pages/about'

  get 'pages/help'

get 'users/show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  nom        :string
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'digest'

class User < ApplicationRecord

  def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
      end

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_accessor :password
  validates :nom, :presence => true,
            :length => {:maximum => 50}

  validates :email, :presence => true,
            :format   => email_regex ,
            :uniqueness => {:case_sensitive => false}

  validates :password, :presence     => true,
            :confirmation => true,
            :length       => { :within => 6..40 }


            before_save :encrypt_password

            def has_password?(password_soumis)
              encrypted_password == encrypt(password_soumis)
            end

  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @titre = "Accueil"
  end

  def contact
    @titre = "Contact"
  end

  def about
    @titre = "Plus d'info"
  end

  def help
    @titre = "Aide"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
      @user = User.new(user_params)
      if @user.save
        flash[:success] = "Bienvenue dans Microposts"
        redirect_to @user
      else
        @titre = "Inscription"
        render 'new'
      end
    end


    def new
      @user = User.new
      @titre = "Inscription"
    end

  def show
    @user = User.find(params[:id])
    @titre = @user.nom
  end

private

  def user_params
        params.require(:user).permit(:nom, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def titre
    base = "Microposts"
    if @titre.nil?
      base
    else
      base + " | " + @titre
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.nom,
                                            :class => 'gravatar',
                                            :gravatar => options)
                                          end
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= titre %> </title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'blueprint-css-master/blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint-css-master/blueprint/print',  :media => 'print' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>
        <%= image_tag("logo.jpg", :alt => "Application Exemple", :class => "lgo") %>
        <nav class="navi">
          <ul>
            <li><%= link_to "Contact", pages_contact_path , :class => "navt"%></li>
            <li><%= link_to "Plus D'infos", pages_about_path ,:class => "navt"%></li>
            <li><%= link_to "Inscription", '#' , :class => "navt"%></li>
          </ul>
        </nav>
      </header>
      <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Microposts</h1>

<p id="intro">
Enregistrez vous pour commencer</p>

<%= link_to "Just Sign In", signup_path , :class => "signup_button round" %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "erreur") %>
        ont empêché d'enregistrer votre inscription</h2>
    <p>Merci de corriger ces champs :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Inscription</h1>

<%= form_for @user do |f| %>

<%= render 'shared/error_messages' %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Inscription" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.nom %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Nom</strong> <%= @user.nom %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>